### ISSUE TITLE
Crear la sección del RESOURCE DESCRIPTION

### ISSUE THREAD

**Issue by efrainpardo88** [efrainpardo88/wookieepedia#18]
**Estimación:**
3sp

**Contexto:**
Route: ~/{category}/{resourceId}

**Evento:**
Resource description

**Descripción:**
Agregar la sección de descripción del recurso en la página de RESOURCE DESCRIPTION

**Resultado esperado:**
Esta sección hace uso del servicio para traer la información del recurso y debe contener:
1. Titulo con el nombre del recurso. Usar `<h1/>` para el título
2. Imagen tipo poster del recurso. Las imágenes se encuentran en la siguiente URL:
    `~/assets/images/[category]/[resource-name].jpg`
3. Al lado de cada imagen deben aparecer los campos descriptivos del recurso. Esto puede hacerse colocando la descripción como texto dentro de un elemento `<p/>` y dentro de este elemento la imagen con un float left.
4. Debajo deben estar los recursos relacionados en modo tarjetas
5. Los recursos relacionados se agrupan por sus categorías, deben tener tener el título de la categoría y la cantidad de recursos que se relacionan
6. Debajo del titulo de la categoría del recurso compartido deben estar los recursos de esta categoría y para mayor comodidad del usuario usar algún componente que los agrupe en una galería de tarjetas, que sea mobile frendly

_Basarse en el diseño de la página_
https://github.com/efrainpardo88/wookieepedia/blob/master/docs/Mockups/Resource.png

**Comment by BriamLeyton** [comment]
se crea el diseño de la pagina en el pull request #40
