### ISSUE TITLE
Crear el proyecto Angular

### ISSUE THREAD

**Issue by efrainpardo88** [efrainpardo88/wookieepedia#4]
**Estimación:**
2sp

**Contexto:**
Aplicación

**Evento:**
N/A

**Descripción:**
Crear el proyecto en el repositorio e instalar todas las dependencias de Angular. Adicional, debe borrarse el archivo todo.txt de la carpeta del proyecto.

**Resultado esperado:**
El proyecto debe crearse en el repositorio, dentro de la carpeta:
https://github.com/efrainpardo88/wookieepedia/tree/master/src/Wookieepedia.UI

**Comment by BriamLeyton** [comment]
se genera el pull request #21 para cerrar este issue

**Comment by efrainpardo88** [comment]
Merged and done!
